import Head from "next/head";
import styles from "@styles/pages/Home.module.scss";
import { Input } from "@components";
import CheckBox from "@components/form/checkbox";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CheckBox task="Create social media accounts" />
      </main>
    </>
  );
}
