import Head from "next/head";
import styles from "@styles/pages/Home.module.scss";
import { Column, Heading, Text } from "@components";

const data = [
  {
    title: "Interview users",
    subtasks: [
      "Make user personas",
      "Ideate solutions",
      "Make initial design in Figma",
    ],
  },
  {
    title: "Make user personas",
    subtasks: [
      "Make user personas",
      "Ideate solutions",
      "Make initial design in Figma",
    ],
  },
  {
    title: "Define main issues to tackle",
    subtasks: [
      "Make user personas",
      "Ideate solutions",
      "Make initial design in Figma",
    ],
  },
  {
    title: "Make initial Figma design",
    subtasks: [
      "Make user personas",
      "Ideate solutions",
      "Make initial design in Figma",
    ],
  },
  {
    title: "Give project to product team",
    subtasks: [
      "Make user personas",
      "Ideate solutions",
      "Make initial design in Figma",
    ],
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Column name="TODO" cards={data} />
      </main>
    </>
  );
}
