import Head from "next/head";
import styles from "@styles/pages/Home.module.scss";
import { Layout } from "@components";
import { DragDropContext } from "react-beautiful-dnd";
import { useDispatch, useSelector } from "react-redux";
import { moveTaskLocal } from "state";

export default function Home() {
  const dispatch = useDispatch();
  const { _id } = useSelector((state: any) => state.global.activeBoard);

  const onDragEnd = (result: any) => {
    const { destination, source, draggableId, type } = result;

    // If user drops the draggable outside of a droppable area
    if (!destination) return;

    // If user drops the draggable in the same place
    if (
      source.droppableId === destination.droppableId &&
      source.index === destination.index
    ) {
      return;
    }

    // If user drops the draggable in a different droppable area
    if (type === "cards") {
      dispatch(
        moveTaskLocal({
          boardId: _id,
          columnId: source.droppableId,
          taskId: draggableId,
          destination,
          source,
        })
      );
    }
    console.log("dnd event: ", result);
  };

  return (
    <>
      <Head>
        <title>Kanban - Task Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DragDropContext onDragEnd={onDragEnd}>
          <Layout />
        </DragDropContext>
      </main>
    </>
  );
}
